CREATE TABLE IF NOT EXISTS ADDRESS  (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  STREET VARCHAR(50) NOT NULL,
  STREET_NUMBER VARCHAR(10),
  CITY VARCHAR(20) NOT NULL,
  ZIP_CODE VARCHAR(10) NOT NULL,
  COUNTRY VARCHAR(20) NOT NULL,
  PRIMARY KEY(ID)
) ENGINE=InnoDB;